# Generated by Django 4.2.9 on 2024-01-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_quill.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_type', models.CharField(choices=[('RESEARCH', 'Research'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('NEWS', 'News')], max_length=250)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('title_ja', models.CharField(max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='POST_thumbnail')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('summary', django_quill.fields.QuillField()),
                ('summary_en', django_quill.fields.QuillField(null=True)),
                ('summary_de', django_quill.fields.QuillField(null=True)),
                ('summary_ja', django_quill.fields.QuillField(null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('content', django_quill.fields.QuillField()),
                ('content_en', django_quill.fields.QuillField(null=True)),
                ('content_de', django_quill.fields.QuillField(null=True)),
                ('content_ja', django_quill.fields.QuillField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('keywords', taggit.managers.TaggableManager(blank=True, help_text='comma seperated keywords', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
