# Generated by Django 4.2.9 on 2024-01-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_content_alter_post_content_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ja',
        ),
    ]
