# Generated by Django 4.2.9 on 2024-01-10 10:35

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_content_de_post_content_en_post_content_ja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_de',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ja',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
    ]
