# Generated by Django 4.2.9 on 2024-01-11 05:08

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_content_alter_post_content_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headers_content',
            field=django_quill.fields.QuillField(default='km'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_cover_photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnail'),
        ),
    ]
