# Generated by Django 4.2.9 on 2024-01-11 06:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_headers_content_alter_post_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headers_content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
