# Generated by Django 4.2.9 on 2024-01-16 11:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_headers_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headers_content_de',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='headers_content_en',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='headers_content_ja',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
