# Generated by Django 4.2.9 on 2024-01-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('RESEARCH', 'Research'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('NEWS', 'News'), ('DATABASE', 'Database'), ('CUSTOMERS', 'Customers')], max_length=250),
        ),
    ]
