# Generated by Django 4.2.9 on 2024-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_url_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
