# Generated by Django 4.2.9 on 2024-01-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_external_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('RESEARCH', 'Research'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('NEWS', 'News'), ('DATABASE', 'Database'), ('CUSTOMERS', 'Customers'), ('EDA', 'Eda')], max_length=250),
        ),
    ]
