# Generated by Django 4.2.9 on 2024-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_url_endpoint',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
